apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jh6ikkt4u-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jh6ikkt4u-dotnet-basic-gitops