apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jh6ikkt4u-dotnet-basic
  janus-idp.io/tekton: jh6ikkt4u-dotnet-basic
  backstage.io/kubernetes-id: jh6ikkt4u-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jh6ikkt4u-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
